# Generated by Django 3.1 on 2020-08-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
                ('time_watered', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToggleWatering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.BooleanField(default=False)),
                ('manual', models.BooleanField(default=False)),
            ],
        ),
    ]
