# Generated by Django 3.1 on 2020-08-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_watered',
            field=models.DateTimeField(),
        ),
    ]
